In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from google.colab import drive

In [2]:
drive.mount('/content/drive/')

Mounted at /content/drive/


In [3]:
movies=pd.read_csv('/content/drive/MyDrive/data/tmdb_5000_movies.csv')
cradits=pd.read_csv('/content/drive/MyDrive/data/tmdb_5000_credits.csv')



**The movie dataset has the following features:-**

    budget - The budget in which the movie was made.
    genre - The genre of the movie, Action, Comedy ,Thriller etc.
    homepage - A link to the homepage of the movie.
    id - This is infact the movie_id as in the first dataset.
    keywords - The keywords or tags related to the movie.
    original_language - The language in which the movie was made.
    original_title - The title of the movie before translation or adaptation.
    overview - A brief description of the movie.
    popularity - A numeric quantity specifying the movie popularity.
    production_companies - The production house of the movie.
    production_countries - The country in which it was produced.
    release_date - The date on which it was released.
    revenue - The worldwide revenue generated by the movie.
    runtime - The running time of the movie in minutes.
    status - "Released" or "Rumored".
    tagline - Movie's tagline.title - Title of the movie.
    vote_average - average ratings the movie recieved.
    vote_count - the count of votes recieved.

    The credits dataset contains the following features:-
    movie_id - A unique identifier for each movie.
    cast - The name of lead and supporting actors.
    crew - The name of Director, Editor, Composer, Writer etc.



**The credits dataset contains the following features:-**

 movie_id - A unique identifier for each movie.
 cast - The name of lead and supporting actors.
 crew - The name of Director, Editor, Composer, Writer etc.

In [4]:
movies.head(2)

budget  ... vote_count
0  237000000  ...      11800
1  300000000  ...       4500

[2 rows x 20 columns]

In [5]:
cradits.head(2)

movie_id  ...                                               crew
0     19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1       285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...

[2 rows x 4 columns]

**Merging both the dataset (movie + credits)** Becuse Needed Movie_id & Cast

In [6]:
movies=movies.merge(cradits,on='title')

In [7]:
movies.head(2)

budget  ...                                               crew
0  237000000  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1  300000000  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...

[2 rows x 23 columns]

In [8]:
# Check Columns Number-
movies.shape

(4809, 23)

In [9]:
# We Access Columns Name is-
# Movie_id
# title
# overview
# genres
#keywords
# cast
#crew


In [10]:
# New dataset Create
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [11]:
movies.shape

(4809, 7)

In [12]:
#check Null calue
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [13]:
# drop null Columns ... 
movies.dropna(inplace=True)

In [14]:
# drop null columns then chek Shape
movies.shape

(4806, 7)

In [15]:
# Locking for Dumpicat Value
movies.duplicated().sum()

0

In [16]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [17]:
movies.iloc[0].title

'Avatar'

In [18]:
movies.iloc[0].overview

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [19]:
movies.iloc[0].crew

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"},

In [20]:
movies.iloc[0].cast

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 

In [21]:

import ast
def convert(obj):
  l=[]
  for i in ast.literal_eval(obj):
    l.append(i['name'])
  return l

In [22]:
movies['genres']=movies['genres'].apply(convert)

In [23]:
movies.iloc[0].genres

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [24]:
movies.iloc[0].keywords

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [25]:
movies['keywords']=movies['keywords'].apply(convert)


In [26]:
movies.head(2)

movie_id  ...                                               crew
0     19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1       285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...

[2 rows x 7 columns]

In [27]:
movies.iloc[0].keywords

['culture clash',
 'future',
 'space war',
 'space colony',
 'society',
 'space travel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alien planet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'love affair',
 'anti war',
 'power relations',
 'mind and soul',
 '3d']

In [28]:
# frist 3 Actors name Count
def convert3(obj):
  L=[]
  count=0
  for i in ast.literal_eval(obj):
    if count<3:
      L.append(i['name'])
      count+=1
  return L

In [29]:
movies['cast']=movies['cast'].apply(convert3)

In [30]:
movies.iloc[0].cast

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver']

In [31]:
movies.head()

movie_id  ...                                               crew
0     19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1       285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2    206647  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     49026  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     49529  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 7 columns]

In [32]:
# Only Director Name Assain

def convertDic(obj):
  L=[]
  for i in ast.literal_eval(obj):
    if i['job']=='Director':
      L.append(i['name'])
  return L


In [33]:
movies['crew']=movies['crew'].apply(convertDic)

In [34]:
movies.iloc[0].crew

['James Cameron']

In [35]:
movies.head()

movie_id  ...                 crew
0     19995  ...      [James Cameron]
1       285  ...     [Gore Verbinski]
2    206647  ...         [Sam Mendes]
3     49026  ...  [Christopher Nolan]
4     49529  ...     [Andrew Stanton]

[5 rows x 7 columns]

In [36]:
# Every Multi word name collapse of flowindly Indentify.
def collapse(obj):
  L=[]
  for i in obj:
    L.append(i.replace(" ",""))
  return L

In [37]:

movies['genres']=movies['genres'].apply(collapse)


In [38]:
movies['keywords']=movies['keywords'].apply(collapse)
movies['cast']=movies['cast'].apply(collapse)
movies['crew']=movies['crew'].apply(collapse)

In [39]:
movies.head()

movie_id  ...                crew
0     19995  ...      [JamesCameron]
1       285  ...     [GoreVerbinski]
2    206647  ...         [SamMendes]
3     49026  ...  [ChristopherNolan]
4     49529  ...     [AndrewStanton]

[5 rows x 7 columns]

In [40]:
x=movies.iloc[2].overview

In [41]:
# avery word user of list
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [42]:
movies.head()

movie_id  ...                crew
0     19995  ...      [JamesCameron]
1       285  ...     [GoreVerbinski]
2    206647  ...         [SamMendes]
3     49026  ...  [ChristopherNolan]
4     49529  ...     [AndrewStanton]

[5 rows x 7 columns]

In [43]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [44]:
new_movies=movies.drop(['overview','genres','keywords','cast','crew'],axis='columns')

In [45]:
new_movies.head()

movie_id  ...                                               tags
0     19995  ...  [In, the, 22nd, century,, a, paraplegic, Marin...
1       285  ...  [Captain, Barbossa,, long, believed, to, be, d...
2    206647  ...  [A, cryptic, message, from, Bond’s, past, send...
3     49026  ...  [Following, the, death, of, District, Attorney...
4     49529  ...  [John, Carter, is, a, war-weary,, former, mili...

[5 rows x 3 columns]

In [46]:
x=new_movies.iloc[0].tags
print(x)

['In', 'the', '22nd', 'century,', 'a', 'paraplegic', 'Marine', 'is', 'dispatched', 'to', 'the', 'moon', 'Pandora', 'on', 'a', 'unique', 'mission,', 'but', 'becomes', 'torn', 'between', 'following', 'orders', 'and', 'protecting', 'an', 'alien', 'civilization.', 'Action', 'Adventure', 'Fantasy', 'ScienceFiction', 'cultureclash', 'future', 'spacewar', 'spacecolony', 'society', 'spacetravel', 'futuristic', 'romance', 'space', 'alien', 'tribe', 'alienplanet', 'cgi', 'marine', 'soldier', 'battle', 'loveaffair', 'antiwar', 'powerrelations', 'mindandsoul', '3d', 'SamWorthington', 'ZoeSaldana', 'SigourneyWeaver', 'JamesCameron']


In [47]:
new_movies['tags'] = new_movies['tags'].apply(lambda x: " ".join(x))
new_movies.head()

movie_id  ...                                               tags
0     19995  ...  In the 22nd century, a paraplegic Marine is di...
1       285  ...  Captain Barbossa, long believed to be dead, ha...
2    206647  ...  A cryptic message from Bond’s past sends him o...
3     49026  ...  Following the death of District Attorney Harve...
4     49529  ...  John Carter is a war-weary, former military ca...

[5 rows x 3 columns]

In [48]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [49]:
vector=cv.fit_transform(new_movies['tags']).toarray()

In [50]:
vector.shape

(4806, 5000)

In [51]:

from sklearn.metrics.pairwise import cosine_similarity


In [52]:


similarity = cosine_similarity(vector)



In [53]:
similarity

array([[1.        , 0.08964215, 0.06071767, ..., 0.02519763, 0.0277885 ,
        0.        ],
       [0.08964215, 1.        , 0.06350006, ..., 0.02635231, 0.        ,
        0.        ],
       [0.06071767, 0.06350006, 1.        , ..., 0.02677398, 0.        ,
        0.        ],
       ...,
       [0.02519763, 0.02635231, 0.02677398, ..., 1.        , 0.07352146,
        0.04774099],
       [0.0277885 , 0.        , 0.        , ..., 0.07352146, 1.        ,
        0.05264981],
       [0.        , 0.        , 0.        , ..., 0.04774099, 0.05264981,
        1.        ]])

In [54]:
new_movies.iloc[0].title

'Avatar'

In [55]:
new_movies[new_movies['title'] == 'The Lego Movie'].index[0]

744

In [56]:
similarity[0]

array([1.        , 0.08964215, 0.06071767, ..., 0.02519763, 0.0277885 ,
       0.        ])

In [57]:
similarity[1]

array([0.08964215, 1.        , 0.06350006, ..., 0.02635231, 0.        ,
       0.        ])

In [58]:
sorted(list(enumerate(similarity[0])),reverse=True,key=(lambda x: x[1]))[1:6]

[(539, 0.26089696604360174),
 (1194, 0.2581988897471611),
 (260, 0.25110592822973776),
 (1216, 0.24944382578492943),
 (507, 0.24846467329894412)]

In [59]:
def recommend(movie):
  movies_index=new_movies[new_movies['title']==movie].index[0]
  distance=similarity[movies_index]
  movies_list=sorted(list(enumerate(distance)),reverse=True,key=(lambda x: x[1]))[1:6]
  for i in movies_list:
    print(new_movies.iloc[i[0]].title)


In [60]:
recommend('Spectre')

Quantum of Solace
Never Say Never Again
Skyfall
Thunderball
From Russia with Love


In [61]:


import pickle



In [62]:


pickle.dump(new_movies,open('/content/drive/MyDrive/Move Recommended/movie_list.pkl','wb'))
pickle.dump(similarity,open('/content/drive/MyDrive/Move Recommended/similarity.pkl','wb'))




In [63]:
new_movies['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [64]:
pickle.dump(new_movies.to_dict(),open('/content/drive/MyDrive/Move Recommended/movies_dit.pkl','wb'))